name: PR Review Auto Comment

on:
  pull_request:
    types: [opened]

jobs:
  add-review-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read review template
        id: get_template
        run: |
          cat .cursor/code-reveiw-template.md > review_comment.txt
      - name: Create review comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('review_comment.txt', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: body
            }); 