name: PR Review Auto Comment

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  add-review-comment:
    if: |
      (github.event_name == 'pull_request') ||
      (github.event.issue.pull_request && (contains(github.event.comment.body, '@review') || contains(github.event.comment.body, '@리뷰하기')))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read review template
        id: get_template
        run: |
          cat .cursor/code-review-template.md > review_comment.txt
      - name: Create review comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('review_comment.txt', 'utf8');
            let issue_number;
            if (github.event_name === 'pull_request') {
              issue_number = context.payload.pull_request.number;
            } else if (github.event_name === 'issue_comment') {
              issue_number = context.payload.issue.number;
            } else {
              throw new Error('지원하지 않는 이벤트입니다.');
            }
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: body
            }); 